In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data/survey_results_public.csv', index_col="Respondent")
schema_df = pd.read_csv('data/survey_results_schema.csv', index_col="Column")

In [29]:
schema_df.sort_index()

                                                             QuestionText
Column
Age                     What is your age (in years)? If you prefer not...
Age1stCode              At what age did you write your first line of c...
BetterLife              Do you think people born today will have a bet...
BlockchainIs            Blockchain / cryptocurrency technology is prim...
BlockchainOrg           How is your organization thinking about or imp...
CareerSat               Overall, how satisfied are you with your caree...
CodeRev                          Do you review code as part of your work?
CodeRevHrs              On average, how many hours per week do you spe...
CompFreq                 Is that compensation weekly, monthly, or yearly?
CompTotal               What is your current total compensation (salar...
Containers              How do you use containers (Docker, Open Contai...
ConvertedComp           Salary converted to annual USD salaries using ...
Country                         In which country do you currently reside?
CurrencyDesc            Which currency do you use day-to-day? If your ...
CurrencySymbol          Which currency do you use day-to-day? If your ...
DatabaseDesireNextYear  Which of the following database environments h...
DatabaseWorkedWith      Which of the following database environments h...
Dependents              Do you have any dependents (e.g., children, el...
DevEnviron              Which development environment(s) do you use re...
DevType                 Which of the following describe you? Please se...
EdLevel                 Which of the following best describes the high...
EduOther                Which of the following types of non-degree edu...
Employment              Which of the following best describes your cur...
EntTeams                Have you ever used Stack Overflow for Enterpri...
Ethnicity               Which of the following do you identify as? Ple...
Extraversion              Do you prefer online chat or IRL conversations?
FizzBuzz                Have you ever been asked to solve FizzBuzz in ...
Gender                  Which of the following do you currently identi...
Hobbyist                                          Do you code as a hobby?
ITperson                 Are you the "IT support person" for your family?
...                                                                   ...
SOAccount                           Do you have a Stack Overflow account?
SOComm                  Do you consider yourself a member of the Stack...
SOFindAnswer            On average, how many times a week do you find ...
SOHowMuchTime           About how much time did you save? If you're no...
SOJobs                  Have you ever used or visited Stack Overflow J...
SONewContent            Would you like to see any of the following on ...
SOPartFreq              How frequently would you say you participate i...
SOTimeSaved             Think back to the last time you solved a codin...
SOVisit1st              To the best of your memory, when did you first...
SOVisitFreq             How frequently would you say you visit Stack O...
SOVisitTo               I visit Stack Overflow to... (check all that a...
ScreenName                                           What do you call it?
Sexuality               Which of the following do you currently identi...
SocialMedia                   What social media site do you use the most?
Student                 Are you currently enrolled in a formal, degree...
SurveyEase              How easy or difficult was this survey to compl...
SurveyLength            How do you feel about the length of the survey...
Trans                                     Do you identify as transgender?
UndergradMajor          What was your main or most important field of ...
UnitTests               Does your company regularly employ unit tests ...
WebFrameDesireNextYear  Which of the following web frameworks have you...
WebFrameWorkedWith      Which of the following web frameworks have you...
WelcomeChange           Compared to last year, how welcome do you feel...
WorkChallenge           Of these options, what are your greatest chall...
WorkLoc                                   Where would you prefer to work?
WorkPlan                          How structured or planned is your work?
WorkRemote                                How often do you work remotely?
WorkWeekHrs              On average, how many hours per week do you work?
YearsCode               Including any education, how many years have y...
YearsCodePro            How many years have you coded professionally (...

[85 rows x 1 columns]

# Aggregate Functions

## All aggregate functions

In [4]:
df.describe()

          CompTotal  ConvertedComp   WorkWeekHrs    CodeRevHrs           Age
count  5.594500e+04   5.582300e+04  64503.000000  49790.000000  79210.000000
mean   5.519014e+11   1.271107e+05     42.127197      5.084308     30.336699
std    7.331926e+13   2.841523e+05     37.287610      5.513931      9.178390
min    0.000000e+00   0.000000e+00      1.000000      0.000000      1.000000
25%    2.000000e+04   2.577750e+04     40.000000      2.000000     24.000000
50%    6.200000e+04   5.728700e+04     40.000000      4.000000     29.000000
75%    1.200000e+05   1.000000e+05     44.750000      6.000000     35.000000
max    1.000000e+16   2.000000e+06   4850.000000     99.000000     99.000000

In [5]:
df['ConvertedComp'].median() # Middle Value

57287.0

In [6]:
df.median() # Find columns that are numerical and gives median

CompTotal        62000.0
ConvertedComp    57287.0
WorkWeekHrs         40.0
CodeRevHrs           4.0
Age                 29.0
dtype: float64

In [7]:
df['ConvertedComp'].std() # Standard Deviation

284152.3038420774

In [8]:
df['ConvertedComp'].count() # Returns all responses excluding NaN, meaning these many people answered the question

55823

In [9]:
# count() != value_counts()

df['Hobbyist'].value_counts()

Yes    71257
No     17626
Name: Hobbyist, dtype: int64

In [10]:
df['SocialMedia'].count() # No of people who responded

84437

In [11]:
df['SocialMedia'].value_counts() # Counts resoponse values

Reddit                      14374
YouTube                     13830
WhatsApp                    13347
Facebook                    13178
Twitter                     11398
Instagram                    6261
I don't use social media     5554
LinkedIn                     4501
WeChat 微信                     667
Snapchat                      628
VK ВКонта́кте                 603
Weibo 新浪微博                     56
Youku Tudou 优酷                 21
Hello                          19
Name: SocialMedia, dtype: int64

In [12]:
df['SocialMedia'].value_counts(normalize=True) # Percentage Values

Reddit                      0.170233
YouTube                     0.163791
WhatsApp                    0.158071
Facebook                    0.156069
Twitter                     0.134988
Instagram                   0.074150
I don't use social media    0.065777
LinkedIn                    0.053306
WeChat 微信                   0.007899
Snapchat                    0.007437
VK ВКонта́кте               0.007141
Weibo 新浪微博                  0.000663
Youku Tudou 优酷              0.000249
Hello                       0.000225
Name: SocialMedia, dtype: float64

# Grouping

## groupby()

In [13]:
df['Country'].value_counts()

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
France                               2391
Brazil                               1948
Poland                               1922
Australia                            1903
Netherlands                          1852
Russian Federation                   1694
Spain                                1604
Italy                                1576
Sweden                               1274
Switzerland                           978
Israel                                952
Turkey                                949
Pakistan                              923
Ukraine                               868
Austria                               839
Czech Republic                        764
Romania                               760
Iran                                  738
Belgium                               727
China                                 664
Bulgaria                              659
Mexico                                642
South Africa                          627
Denmark                               617
Bangladesh                            605
                                    ...
Guyana                                  3
Lesotho                                 3
Guinea                                  3
Cape Verde                              3
Belize                                  3
Lao People's Democratic Republic        3
Mali                                    3
Liechtenstein                           3
Burundi                                 3
Barbados                                3
Bahamas                                 3
Malawi                                  2
Gabon                                   2
Djibouti                                2
Liberia                                 2
Bhutan                                  2
Seychelles                              2
San Marino                              2
Sierra Leone                            2
North Korea                             1
Niger                                   1
Tonga                                   1
Sao Tome and Principe                   1
Papua New Guinea                        1
Brunei Darussalam                       1
Dominica                                1
Saint Vincent and the Grenadines        1
Chad                                    1
Timor-Leste                             1
Saint Kitts and Nevis                   1
Name: Country, Length: 179, dtype: int64

In [14]:
country_grp = df.groupby(['Country'])

In [15]:
country_grp.get_group('India')

#The above is similar to:

# filt = df['Country'] == 'India'
# df.loc[filt]

,MainBranch,Hobbyist,OpenSourcer,OpenSource,Employment,Country,Student,EdLevel,UndergradMajor,EduOther,...,WelcomeChange,SONewContent,Age,Gender,Trans,Sexuality,Ethnicity,Dependents,SurveyLength,SurveyEase
Respondent,,,,,,,,,,,,,,,,,,,,,
8,I code primarily as a hobby,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Neither easy nor difficult
10,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Somewhat less welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,Yes,Too long,Difficult
15,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,20.0,Man,No,NaN,NaN,Yes,Too long,Neither easy nor difficult
50,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,23.0,Man,No,NaN,South Asian,No,Too long,Easy
65,I am a developer by profession,Yes,Never,NaN,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",NaN,...,A lot more welcome now than last year,NaN,21.0,Man,No,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
68,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
75,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Courses on technologies you're interested in,27.0,Woman,No,Straight / Heterosexual,NaN,No,Too long,Neither easy nor difficult
78,I am a developer by profession,No,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Received on-the-job training in software devel...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,25.0,Man,No,NaN,NaN,Yes,Appropriate in length,Easy
83,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Industry news about technologies you're intere...,22.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Neither easy nor difficult
89,I am a student who is learning to code,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",India,No,Some college/university study without earning ...,"Computer science, computer engineering, or sof...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,No,Bisexual,East Asian,Yes,Too short,Easy
90,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Easy
99,I am a student who is learning to code,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed part-time,India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Industry news about technologies you're intere...,21.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Neither easy nor difficult
104,I am a developer by profession,Yes,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken a part-time in-person course in programm...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
121,I am a student who is learning to code,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Independent contractor, freelancer, or self-em...",India,"Yes, full-time","Secondary school (e.g. American high school, G...",NaN,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,20.0,Man,No,Straight / Heterosexual,South Asian,No,Too long,Neither easy nor difficult
124,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,...,A lot more welcome now than last year,Tech articles written by other developers;Cour...,27.0,Man,No,Bisexual,South Asian,NaN,Too long,Easy
140,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...","Taught yourself a new language, framework, or ...",...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,25.0,Man,No,Straight / Heterosexual,NaN,NaN,Too long,Easy
169,I am a developer by profession,No,Less than once per year,The quality of OSS and closed source software ...,NaN,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Contributed to open source software,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,32.0,Man,No,NaN,East Asian,Yes,Too long,Neither easy nor difficult
174,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Industry news about technologies you're intere...,24.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
176,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Completed an industry certification program (e...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,East Asian,Yes,Appropriate in length,Easy
178,I am a developer by profession,Yes,Once a month or more often,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",India,"Yes, full-time",NaN,"Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,28.0,Man,NaN,Bisexual,South Asian,Yes,Too long,Easy
220,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","A business discipline (ex. accounting, finance...",Participated in a full-time developer training...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,NaN,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Easy
238,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, part-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,31.0,Man,No,Straight / Heterosexual,NaN,Yes,Appropriate in length,Easy
239,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Tech...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
242,I am a developer by profession,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",NaN,...,A lot more welcome now than last year,Courses on technologies you're interested in,30.0,Man,NaN,NaN,NaN,Yes,Appropriate in length,Neither easy nor difficult
263,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,NaN,40.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
271,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)",Web development or web design,Taken an online course in programming or softw...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Tech...,24.0,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Easy
288,I am a developer by profession,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",NaN,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,NaN,Man,No,Bisexual,South Asian,Yes,Too long,Easy
291,I am a developer by profession,No,Never,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","Computer science, computer engineering, or sof...",NaN,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,NaN,Straight / Heterosexual,South Asian,NaN,Too long,Easy
343,I am a developer by profession,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Participated in online coding competitions (e....,...,Somewhat more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Woman,No,NaN,NaN,Yes,Too long,Easy
344,I am a developer by profession,Yes,Less than once a month but more than once per ...,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Another engineering discipline (ex. civil, ele...",Received on-the-job training in software devel...,...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,29.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Neither easy nor difficult
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
88843,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Industry news about technologies you're intere...,22.0,Man,No,Straight / Heterosexual,South Asian,Yes,Appropriate in length,Easy
88856,I am a developer by profession,Yes,Never,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)",Web development or web design,Participated in online coding competitions (e....,...,Somewhat less welcome now than last year,Tech articles written by other developers;Indu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
88869,I am a developer by profession,No,Never,"OSS is, on average, of LOWER quality than prop...",Employed full-time,India,NaN,NaN,NaN,NaN,...,A lot more welcome now than last year,Tech articles written by other developers,30.0,Man,No,NaN,South Asian,No,Too long,Neither easy nor difficult
88872,I am a developer by profession,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,No,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,Somewhat more welcome now than last year,Tech articles written by other developers;Cour...,NaN,Man,No,NaN,NaN,Yes,NaN,Neither easy nor difficult
14444,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Independent contractor, freelancer, or self-em...",India,"Yes, full-time",Some college/university study without earning ...,NaN,NaN,...,Not applicable - I did not use Stack Overflow ...,Tech articles written by other developers;Indu...,NaN,NaN,No,Bisexual,NaN,NaN,Too short,Neither easy nor difficult
20000,NaN,Yes,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,"Yes, full-time","Bachelor’s degree (BA, BS, B.Eng., etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,...,A lot less welcome now than last year,Tech articles written by other developers;Indu...,28.0,Man,No,NaN,South Asian,NaN,Too long,NaN
20567,NaN,Yes,Less than once a month but more than once per ...,"OSS is, on average, of HIGHER quality than pro...","Not employed, and not looking for work",India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)","A natural science (ex. biology, chemistry, phy...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,22.0,Man,No,Straight / Heterosexual,South Asian,No,Appropriate in length,Easy
20892,NaN,No,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, part-time",NaN,"Another engineering discipline (ex. civil, ele...","Taught yourself a new language, framework, or ...",...,NaN,NaN,43.0,Man,No,NaN,NaN,Yes,Too long,Easy
21826,NaN,Yes,Less than once per year,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time",NaN,Web development or web design,Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers,22.0,Man,No,NaN,South Asian,Yes,Appropriate in length,Easy
24606,NaN,Yes,Once a month or more often,"OSS is, on average, of HIGHER quality than pro...",Employed full-time,India,NaN,Associate degree,NaN,Taken a part-time in-person course in programm...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25114,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed part-time,India,"Yes, part-time","Bachelor’s degree (BA, BS, B.Eng., etc.)",Mathematics or statistics,NaN,...,Just as welcome now as I felt last year,Tech meetups or events in your area,22.0,Man,NaN,NaN,NaN,NaN,Appropriate in length,Neither easy nor difficult
26419,NaN,No,Less than once per year,The quality of OSS and closed source software ...,"Not employed, but looking for work",India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...",Taken an online course in programming or softw...,...,A lot more welcome now than last year,Tech articles written by other developers;Indu...,24.0,Woman,No,Straight / Heterosexual,NaN,NaN,Too long,Neither easy nor difficult
27229,NaN,Yes,Never,The quality of OSS and closed source software ...,Employed full-time,India,No,"Master’s degree (MA, MS, M.Eng., MBA, etc.)","Information systems, information technology, o...","Taught yourself a new language, framework, or ...",...,Just as welcome now as I felt last year,Tech articles written by other developers;Indu...,34.0,Man,No,NaN,South Asian,Yes,Too long,Easy
35010,NaN,Yes,Never,The quality of OSS and closed source software ...,NaN,India,No,Primary/elementary school,NaN,Participated in a full-time developer training...,...,NaN,Tech articles written by other developers,NaN,Man,NaN,NaN,South Asian,Yes,Appropriate in length,Neither easy nor difficult
40151,NaN,No,Less than once per year,"OSS is, on average, of HIGHER quality than pro...",NaN,India,No,"Secondary school (e.g. American high school, G...",NaN,NaN,...,A lot more welcome now than last year,Tech meetups or events in your area,NaN,Man,No,Straight / Heterosexual,South Asian,Yes,Too long,Neither easy nor difficult
40898,NaN,Yes,Never,"OSS is, on average, of HIGHER quality than pro...","Not employed, but looking for work",India,NaN,"Bachelor’s degree (BA, BS, B.Eng., etc.)","Computer science, computer engineering, or sof...",Taken an online course in programming or softw...,...,NaN,Tech articles written by other developers;Tech...,NaN,Man,No,Straight / Heterosexual,NaN,NaN,Appropriate in length,Easy
42599,NaN,No,Once a month or more often,The quality of OSS and closed source software ...,Employed full-time,India,"Yes, full-time","Master’s degree (MA, MS, M.Eng., MBA, etc.)",NaN,NaN,...,Not applicable - I did not use Stack Overflow ...,NaN,30.0,Man,No,Straight / Heterosexual,NaN,Yes,Too long,Neither easy nor difficult

In [16]:
country_grp.get_group('India')['SocialMedia'].value_counts()

WhatsApp                    2990
YouTube                     1820
LinkedIn                     955
Facebook                     841
Instagram                    822
Twitter                      542
Reddit                       473
I don't use social media     250
Snapchat                      23
Hello                          5
WeChat 微信                      5
VK ВКонта́кте                  4
Youku Tudou 优酷                 2
Weibo 新浪微博                     1
Name: SocialMedia, dtype: int64

In [17]:
country_grp['SocialMedia'].value_counts()

Country                               SocialMedia
Afghanistan                           Facebook                     15
                                      YouTube                       9
                                      I don't use social media      6
                                      WhatsApp                      4
                                      Instagram                     1
                                      LinkedIn                      1
                                      Twitter                       1
Albania                               WhatsApp                     18
                                      Facebook                     16
                                      Instagram                    13
                                      YouTube                      10
                                      Twitter                       8
                                      LinkedIn                      7
                                      Reddit                        6
                                      I don't use social media      4
                                      Snapchat                      1
                                      WeChat 微信                     1
Algeria                               YouTube                      42
                                      Facebook                     41
                                      Twitter                      14
                                      LinkedIn                      9
                                      I don't use social media      7
                                      Instagram                     7
                                      Reddit                        2
                                      WhatsApp                      2
Andorra                               Facebook                      2
                                      I don't use social media      2
                                      Reddit                        1
                                      Snapchat                      1
                                      YouTube                       1
                                                                 ...
Venezuela, Bolivarian Republic of...  Facebook                     10
                                      Reddit                        6
                                      I don't use social media      4
                                      LinkedIn                      1
Viet Nam                              Facebook                    129
                                      YouTube                      44
                                      Reddit                       21
                                      Twitter                       8
                                      I don't use social media      7
                                      Instagram                     6
                                      LinkedIn                      3
                                      WhatsApp                      3
                                      Hello                         1
Yemen                                 WhatsApp                      8
                                      Facebook                      5
                                      YouTube                       5
                                      Twitter                       1
Zambia                                Facebook                      4
                                      Twitter                       2
                                      WhatsApp                      2
                                      YouTube                       2
                                      LinkedIn                      1
                                      Reddit                        1
Zimbabwe                              WhatsApp                     20
                                      Twitter                       8
                                      Facebook                      3
                                      YouTube                       3
                                      Instagram                     2
                                      LinkedIn                      2
                                      Reddit                        1
Name: SocialMedia, Length: 1220, dtype: int64

In [21]:
country_grp['ConvertedComp'].median()

Country
Afghanistan                                    6222.0
Albania                                       10818.0
Algeria                                        7878.0
Andorra                                      160931.0
Angola                                         7764.0
Antigua and Barbuda                               NaN
Argentina                                     17760.0
Armenia                                       19692.0
Australia                                     79783.0
Austria                                       51559.0
Azerbaijan                                    15858.0
Bahamas                                           NaN
Bahrain                                       15912.0
Bangladesh                                     8764.0
Barbados                                      21000.0
Belarus                                       24000.0
Belgium                                       48120.0
Belize                                            NaN
Benin                                             NaN
Bhutan                                            NaN
Bolivia                                       13020.0
Bosnia and Herzegovina                        18360.0
Botswana                                      38410.0
Brazil                                        18036.0
Brunei Darussalam                              6096.0
Bulgaria                                      28080.0
Burkina Faso                                   8388.0
Burundi                                        3606.0
Cambodia                                      10420.0
Cameroon                                       6288.0
                                               ...
Sri Lanka                                      7476.0
Sudan                                          2016.0
Swaziland                                     62371.0
Sweden                                        56004.0
Switzerland                                   95440.0
Syrian Arab Republic                           2742.0
Taiwan                                        27954.0
Tajikistan                                     4902.0
Thailand                                      30672.0
The former Yugoslav Republic of Macedonia     21996.0
Timor-Leste                                  229500.0
Togo                                           4188.0
Tonga                                             NaN
Trinidad and Tobago                           27828.0
Tunisia                                        6468.0
Turkey                                        17280.0
Turkmenistan                                  27348.0
Uganda                                         5490.0
Ukraine                                       26940.0
United Arab Emirates                          49008.0
United Kingdom                                68041.0
United Republic of Tanzania                    5192.0
United States                                110000.0
Uruguay                                       33850.0
Uzbekistan                                     7176.0
Venezuela, Bolivarian Republic of...           6384.0
Viet Nam                                      11892.0
Yemen                                         11940.0
Zambia                                         5040.0
Zimbabwe                                      19200.0
Name: ConvertedComp, Length: 179, dtype: float64

In [22]:
country_grp['ConvertedComp'].median().loc['India']

10080.0

## agg()

Adds more than one aggregate function to group

In [23]:
country_grp['ConvertedComp'].agg(['median', 'mean'])

                                             median           mean
Country
Afghanistan                                  6222.0  101953.333333
Albania                                     10818.0   21833.700000
Algeria                                      7878.0   34924.047619
Andorra                                    160931.0  160931.000000
Angola                                       7764.0    7764.000000
Antigua and Barbuda                             NaN            NaN
Argentina                                   17760.0   29467.265306
Armenia                                     19692.0   24691.733333
Australia                                   79783.0  171541.116279
Austria                                     51559.0   83955.639604
Azerbaijan                                  15858.0   15785.750000
Bahamas                                         NaN            NaN
Bahrain                                     15912.0   23934.000000
Bangladesh                                   8764.0   21249.652000
Barbados                                    21000.0   21000.000000
Belarus                                     24000.0   29442.330645
Belgium                                     48120.0   73185.564655
Belize                                          NaN            NaN
Benin                                           NaN            NaN
Bhutan                                          NaN            NaN
Bolivia                                     13020.0   17977.360000
Bosnia and Herzegovina                      18360.0   24996.283333
Botswana                                    38410.0   40994.000000
Brazil                                      18036.0   32623.570000
Brunei Darussalam                            6096.0    6096.000000
Bulgaria                                    28080.0   42642.419355
Burkina Faso                                 8388.0    8388.000000
Burundi                                      3606.0    3606.000000
Cambodia                                    10420.0   31957.000000
Cameroon                                     6288.0   24194.913043
...                                             ...            ...
Sri Lanka                                    7476.0   13568.012121
Sudan                                        2016.0    5195.333333
Swaziland                                   62371.0  242607.500000
Sweden                                      56004.0   76865.636163
Switzerland                                 95440.0  172675.602679
Syrian Arab Republic                         2742.0    3562.500000
Taiwan                                      27954.0   40364.712963
Tajikistan                                   4902.0    4902.000000
Thailand                                    30672.0   48379.436893
The former Yugoslav Republic of Macedonia   21996.0   40389.451613
Timor-Leste                                229500.0  229500.000000
Togo                                         4188.0    4188.000000
Tonga                                           NaN            NaN
Trinidad and Tobago                         27828.0   50346.777778
Tunisia                                      6468.0   10130.129630
Turkey                                      17280.0   25133.222664
Turkmenistan                                27348.0   46449.333333
Uganda                                       5490.0   37974.352941
Ukraine                                     26940.0   32698.136531
United Arab Emirates                        49008.0   53545.659091
United Kingdom                              68041.0  166182.499504
United Republic of Tanzania                  5192.0   34691.117647
United States                              110000.0  249546.254589
Uruguay                                     33850.0   53862.571429
Uzbekistan                                   7176.0   18304.142857
Venezuela, Bolivarian Republic of...         6384.0   14581.627907
Viet Nam                                    11892.0   17233.436782
Yemen                                       11940.0   16909.166667
Zambia                                       5040.0   10075.375000
Zimbabwe                                    19200.0   34046.666667

[179 rows x 2 columns]

In [34]:
filt = df['Country'] == 'India'

df.loc[filt]['LanguageWorkedWith'].str.contains('Python').value_counts()

False    5739
True     3105
Name: LanguageWorkedWith, dtype: int64

In [35]:
country_grp['LanguageWorkedWith'].str.contains('Python').value_counts()

AttributeError: Cannot access attribute 'str' of 'SeriesGroupBy' objects, try using the 'apply' method

In [42]:
country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

Country
Afghanistan                                      8
Albania                                         23
Algeria                                         40
Andorra                                          0
Angola                                           2
Antigua and Barbuda                              0
Argentina                                      191
Armenia                                         28
Australia                                      790
Austria                                        338
Azerbaijan                                      17
Bahamas                                          2
Bahrain                                          4
Bangladesh                                     204
Barbados                                         1
Belarus                                         69
Belgium                                        296
Belize                                           1
Benin                                            3
Bhutan                                           1
Bolivia                                         11
Bosnia and Herzegovina                          29
Botswana                                         1
Brazil                                         767
Brunei Darussalam                                0
Bulgaria                                       181
Burkina Faso                                     0
Burundi                                          1
Cambodia                                         9
Cameroon                                        16
                                             ...
Sri Lanka                                      137
Sudan                                           16
Swaziland                                        2
Sweden                                         496
Switzerland                                    460
Syrian Arab Republic                             7
Taiwan                                          88
Tajikistan                                       0
Thailand                                        92
The former Yugoslav Republic of Macedonia        8
Timor-Leste                                      1
Togo                                             1
Tonga                                            0
Trinidad and Tobago                              5
Tunisia                                         40
Turkey                                         371
Turkmenistan                                     6
Uganda                                          47
Ukraine                                        246
United Arab Emirates                            49
United Kingdom                                2384
United Republic of Tanzania                     15
United States                                10083
Uruguay                                         36
Uzbekistan                                      14
Venezuela, Bolivarian Republic of...            28
Viet Nam                                        78
Yemen                                            3
Zambia                                           4
Zimbabwe                                        14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [45]:
# Percentage of people in each country know Python

country_respondents = df['Country'].value_counts()

country_respondents

United States                       20949
India                                9061
Germany                              5866
United Kingdom                       5737
Canada                               3395
France                               2391
Brazil                               1948
Poland                               1922
Australia                            1903
Netherlands                          1852
Russian Federation                   1694
Spain                                1604
Italy                                1576
Sweden                               1274
Switzerland                           978
Israel                                952
Turkey                                949
Pakistan                              923
Ukraine                               868
Austria                               839
Czech Republic                        764
Romania                               760
Iran                                  738
Belgium                               727
China                                 664
Bulgaria                              659
Mexico                                642
South Africa                          627
Denmark                               617
Bangladesh                            605
                                    ...
Guyana                                  3
Lesotho                                 3
Guinea                                  3
Cape Verde                              3
Belize                                  3
Lao People's Democratic Republic        3
Mali                                    3
Liechtenstein                           3
Burundi                                 3
Barbados                                3
Bahamas                                 3
Malawi                                  2
Gabon                                   2
Djibouti                                2
Liberia                                 2
Bhutan                                  2
Seychelles                              2
San Marino                              2
Sierra Leone                            2
North Korea                             1
Niger                                   1
Tonga                                   1
Sao Tome and Principe                   1
Papua New Guinea                        1
Brunei Darussalam                       1
Dominica                                1
Saint Vincent and the Grenadines        1
Chad                                    1
Timor-Leste                             1
Saint Kitts and Nevis                   1
Name: Country, Length: 179, dtype: int64

In [47]:
country_uses_python = country_grp['LanguageWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

country_uses_python

Country
Afghanistan                                      8
Albania                                         23
Algeria                                         40
Andorra                                          0
Angola                                           2
Antigua and Barbuda                              0
Argentina                                      191
Armenia                                         28
Australia                                      790
Austria                                        338
Azerbaijan                                      17
Bahamas                                          2
Bahrain                                          4
Bangladesh                                     204
Barbados                                         1
Belarus                                         69
Belgium                                        296
Belize                                           1
Benin                                            3
Bhutan                                           1
Bolivia                                         11
Bosnia and Herzegovina                          29
Botswana                                         1
Brazil                                         767
Brunei Darussalam                                0
Bulgaria                                       181
Burkina Faso                                     0
Burundi                                          1
Cambodia                                         9
Cameroon                                        16
                                             ...
Sri Lanka                                      137
Sudan                                           16
Swaziland                                        2
Sweden                                         496
Switzerland                                    460
Syrian Arab Republic                             7
Taiwan                                          88
Tajikistan                                       0
Thailand                                        92
The former Yugoslav Republic of Macedonia        8
Timor-Leste                                      1
Togo                                             1
Tonga                                            0
Trinidad and Tobago                              5
Tunisia                                         40
Turkey                                         371
Turkmenistan                                     6
Uganda                                          47
Ukraine                                        246
United Arab Emirates                            49
United Kingdom                                2384
United Republic of Tanzania                     15
United States                                10083
Uruguay                                         36
Uzbekistan                                      14
Venezuela, Bolivarian Republic of...            28
Viet Nam                                        78
Yemen                                            3
Zambia                                           4
Zimbabwe                                        14
Name: LanguageWorkedWith, Length: 179, dtype: int64

In [50]:
python_df = pd.concat([country_respondents, country_uses_python], axis='columns', sort=False)

python_df

                                  Country  LanguageWorkedWith
United States                       20949               10083
India                                9061                3105
Germany                              5866                2451
United Kingdom                       5737                2384
Canada                               3395                1558
France                               2391                1054
Brazil                               1948                 767
Poland                               1922                 751
Australia                            1903                 790
Netherlands                          1852                 767
Russian Federation                   1694                 708
Spain                                1604                 641
Italy                                1576                 625
Sweden                               1274                 496
Switzerland                           978                 460
Israel                                952                 457
Turkey                                949                 371
Pakistan                              923                 251
Ukraine                               868                 246
Austria                               839                 338
Czech Republic                        764                 285
Romania                               760                 253
Iran                                  738                 268
Belgium                               727                 296
China                                 664                 297
Bulgaria                              659                 181
Mexico                                642                 245
South Africa                          627                 202
Denmark                               617                 246
Bangladesh                            605                 204
...                                   ...                 ...
Guyana                                  3                   2
Lesotho                                 3                   1
Guinea                                  3                   2
Cape Verde                              3                   0
Belize                                  3                   1
Lao People's Democratic Republic        3                   0
Mali                                    3                   1
Liechtenstein                           3                   1
Burundi                                 3                   1
Barbados                                3                   1
Bahamas                                 3                   2
Malawi                                  2                   0
Gabon                                   2                   0
Djibouti                                2                   0
Liberia                                 2                   0
Bhutan                                  2                   1
Seychelles                              2                   1
San Marino                              2                   1
Sierra Leone                            2                   1
North Korea                             1                   0
Niger                                   1                   1
Tonga                                   1                   0
Sao Tome and Principe                   1                   1
Papua New Guinea                        1                   0
Brunei Darussalam                       1                   0
Dominica                                1                   1
Saint Vincent and the Grenadines        1                   0
Chad                                    1                   0
Timor-Leste                             1                   1
Saint Kitts and Nevis                   1                   0

[179 rows x 2 columns]

In [53]:
python_df = python_df.rename(columns={'Country': 'NumRespondents', 'LanguageWorkedWith': 'NumKnowsPython'})

python_df

                                  NumRespondents  NumKnowsPython
United States                              20949           10083
India                                       9061            3105
Germany                                     5866            2451
United Kingdom                              5737            2384
Canada                                      3395            1558
France                                      2391            1054
Brazil                                      1948             767
Poland                                      1922             751
Australia                                   1903             790
Netherlands                                 1852             767
Russian Federation                          1694             708
Spain                                       1604             641
Italy                                       1576             625
Sweden                                      1274             496
Switzerland                                  978             460
Israel                                       952             457
Turkey                                       949             371
Pakistan                                     923             251
Ukraine                                      868             246
Austria                                      839             338
Czech Republic                               764             285
Romania                                      760             253
Iran                                         738             268
Belgium                                      727             296
China                                        664             297
Bulgaria                                     659             181
Mexico                                       642             245
South Africa                                 627             202
Denmark                                      617             246
Bangladesh                                   605             204
...                                          ...             ...
Guyana                                         3               2
Lesotho                                        3               1
Guinea                                         3               2
Cape Verde                                     3               0
Belize                                         3               1
Lao People's Democratic Republic               3               0
Mali                                           3               1
Liechtenstein                                  3               1
Burundi                                        3               1
Barbados                                       3               1
Bahamas                                        3               2
Malawi                                         2               0
Gabon                                          2               0
Djibouti                                       2               0
Liberia                                        2               0
Bhutan                                         2               1
Seychelles                                     2               1
San Marino                                     2               1
Sierra Leone                                   2               1
North Korea                                    1               0
Niger                                          1               1
Tonga                                          1               0
Sao Tome and Principe                          1               1
Papua New Guinea                               1               0
Brunei Darussalam                              1               0
Dominica                                       1               1
Saint Vincent and the Grenadines               1               0
Chad                                           1               0
Timor-Leste                                    1               1
Saint Kitts and Nevis                          1               0

[179 rows x 2 columns]

In [59]:
python_df['PercentageKnowsPython'] = python_df['NumKnowsPython'] *100 / python_df['NumRespondents'] 

python_df

,NumRespondents,NumKnowsPython,PercentageKnowsPython
United States,20949,10083,48.131176
India,9061,3105,34.267741
Germany,5866,2451,41.783157
United Kingdom,5737,2384,41.554820
Canada,3395,1558,45.891016
France,2391,1054,44.081974
Brazil,1948,767,39.373717
Poland,1922,751,39.073881
Australia,1903,790,41.513400
Netherlands,1852,767,41.414687
Russian Federation,1694,708,41.794569
Spain,1604,641,39.962594
Italy,1576,625,39.657360
Sweden,1274,496,38.932496
Switzerland,978,460,47.034765
Israel,952,457,48.004202
Turkey,949,371,39.093783
Pakistan,923,251,27.193933
Ukraine,868,246,28.341014
Austria,839,338,40.286055
Czech Republic,764,285,37.303665
Romania,760,253,33.289474
Iran,738,268,36.314363
Belgium,727,296,40.715268
China,664,297,44.728916
Bulgaria,659,181,27.465857
Mexico,642,245,38.161994
South Africa,627,202,32.216906
Denmark,617,246,39.870340
Bangladesh,605,204,33.719008
...,...,...,...
Guyana,3,2,66.666667
Lesotho,3,1,33.333333
Guinea,3,2,66.666667
Cape Verde,3,0,0.000000
Belize,3,1,33.333333
Lao People's Democratic Republic,3,0,0.000000
Mali,3,1,33.333333
Liechtenstein,3,1,33.333333
Burundi,3,1,33.333333
Barbados,3,1,33.333333
Bahamas,3,2,66.666667
Malawi,2,0,0.000000
Gabon,2,0,0.000000
Djibouti,2,0,0.000000
Liberia,2,0,0.000000
Bhutan,2,1,50.000000
Seychelles,2,1,50.000000
San Marino,2,1,50.000000
Sierra Leone,2,1,50.000000
North Korea,1,0,0.000000
Niger,1,1,100.000000
Tonga,1,0,0.000000
Sao Tome and Principe,1,1,100.000000
Papua New Guinea,1,0,0.000000
Brunei Darussalam,1,0,0.000000
Dominica,1,1,100.000000
Saint Vincent and the Grenadines,1,0,0.000000
Chad,1,0,0.000000
Timor-Leste,1,1,100.000000
Saint Kitts and Nevis,1,0,0.000000

In [61]:
python_df.sort_values(by='PercentageKnowsPython', ascending=False, inplace=True)

python_df

,NumRespondents,NumKnowsPython,PercentageKnowsPython
Niger,1,1,100.000000
Sao Tome and Principe,1,1,100.000000
Timor-Leste,1,1,100.000000
Dominica,1,1,100.000000
Turkmenistan,7,6,85.714286
Mauritania,7,5,71.428571
Bahamas,3,2,66.666667
Guyana,3,2,66.666667
Guinea,3,2,66.666667
Uganda,72,47,65.277778
Iceland,49,30,61.224490
Namibia,5,3,60.000000
Benin,5,3,60.000000
Haiti,5,3,60.000000
"Congo, Republic of the...",7,4,57.142857
Oman,11,6,54.545455
Cuba,30,16,53.333333
Republic of Korea,39,20,51.282051
Seychelles,2,1,50.000000
Sierra Leone,2,1,50.000000
San Marino,2,1,50.000000
Bhutan,2,1,50.000000
Monaco,4,2,50.000000
South Korea,160,80,50.000000
Chile,206,102,49.514563
Finland,546,266,48.717949
Kenya,249,120,48.192771
United States,20949,10083,48.131176
Israel,952,457,48.004202
Ecuador,82,39,47.560976
...,...,...,...
Kazakhstan,64,15,23.437500
Somalia,13,3,23.076923
Bahrain,18,4,22.222222
Dominican Republic,97,21,21.649485
Botswana,5,1,20.000000
Fiji,5,1,20.000000
Libyan Arab Jamahiriya,10,2,20.000000
Afghanistan,44,8,18.181818
Myanmar,52,9,17.307692
Republic of Moldova,43,7,16.279070
Yemen,19,3,15.789474
The former Yugoslav Republic of Macedonia,54,8,14.814815
Mozambique,7,1,14.285714
Tonga,1,0,0.000000
Liberia,2,0,0.000000
Malawi,2,0,0.000000
Lao People's Democratic Republic,3,0,0.000000
Cape Verde,3,0,0.000000
Burkina Faso,4,0,0.000000
North Korea,1,0,0.000000
Andorra,7,0,0.000000
Papua New Guinea,1,0,0.000000
Tajikistan,7,0,0.000000
Brunei Darussalam,1,0,0.000000
Saint Vincent and the Grenadines,1,0,0.000000
Chad,1,0,0.000000
Antigua and Barbuda,9,0,0.000000
Djibouti,2,0,0.000000
Gabon,2,0,0.000000
Saint Kitts and Nevis,1,0,0.000000

In [63]:
python_df.loc['India']

NumRespondents           9061.000000
NumKnowsPython           3105.000000
PercentageKnowsPython      34.267741
Name: India, dtype: float64